import { Metadata } from "next";
import "./page.scss";

export const metadata: Metadata = {
  title: "Protected Page",
  description: "Generated by create next app",
};

async function formAction(formData: FormData) {
  "use server";
  const title = formData.get("title");
  const content = formData.get("content");
  const tags = formData.get("tags");
  console.log({ title, content, tags });
}

export default function Protected() {
  console.log("\n\x1b[34m[pages/protected]\x1b[0m");

  return (
    <main className="protected">
      <section>
        <h1>Protected Page(dashboard, account, ... etc)</h1>
        <form action={formAction}>
          <input type="text" name="title" placeholder="title" />
          <textarea name="content" placeholder="content" />
          <input type="text" name="tags" placeholder="tags" />
          <button type="submit">public (게시하기)</button>
        </form>
        <div className="something"></div>
      </section>
    </main>
  );
}
