"use client";

import { useFormState } from "react-dom";
// import { Metadata } from "next";
import "./page.scss";
import { createPost } from "@/app/post/create/actions";

// export const metadata: Metadata = {
//   title: "Post Create",
//   description: "Generated by create next app",
// };

export default function PostCreate() {
  // console.log("\n[post-create-page]");

  const [state, formAction]: any = useFormState((prevState: any, formData: FormData) => {
    createPost(formData, localStorage.getItem("accessToken") as string);
  }, undefined);
  console.log({ state });

  return (
    <main className="post-create-page">
      <section>
        <h1>Post Create Page</h1>
        <form
          action={
            // (params: any) =>
            // formAction(params, localStorage.getItem("accessToken") as string)
            formAction
          }
        >
          <input type="text" name="category" placeholder="category" />
          <input type="text" name="title" placeholder="title" />
          <textarea name="content" placeholder="content" />
          <input type="text" name="author" placeholder="author" />
          <input type="text" name="tags" placeholder="tags" />
          <button type="submit">publish (게시하기)</button>
        </form>
      </section>
    </main>
  );
}
