import { Metadata } from "next";
import "./page.scss";

export const metadata: Metadata = {
  title: "Post Create",
  description: "Generated by create next app",
};

async function formAction(formData: FormData) {
  "use server";
  const title = formData.get("title");
  const content = formData.get("content");
  const tags = formData.get("tags");
  console.log({ title, content, tags });
}

export default function PostCreate() {
  console.log("\n[post-create-page]");

  return (
    <main className="post-create-page">
      <section>
        <h1>Post Create Page</h1>
        <form action={formAction}>
          <input type="text" name="title" placeholder="title" />
          <textarea name="content" placeholder="content" />
          <input type="text" name="tags" placeholder="tags" />
          <button type="submit">publish (게시하기)</button>
        </form>
        <div className="something"></div>
      </section>
    </main>
  );
}
