name: Warm Up Vercel Functions

on:
  schedule:
    - cron: "*/5 * * * *" # 5분마다 실행

jobs:
  warmup:
    runs-on: ubuntu-latest
    steps:
      - name: Warm Up Function
        run: curl -X GET https://blog-next-app-three.vercel.app/api/warmup
